import csv
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TEST_TMP = ROOT / ".test-tmp"


def write_synthetic_libre(path):
    rows = [
        ["LibreView Device Data"],
        ["Patient Name", "Jane Example"],
        ["Date of Birth", "1977-04-03"],
        ["Device", "FreeStyle Libre 2"],
        ["Device Timestamp", "Record Type", "Historic Glucose mmol/L"],
        ["2026-01-01 00:00", "0", "5.4"],
        ["2026-01-01 00:15", "0", "5.7"],
        ["2026-01-01 00:30", "0", "6.1"],
    ]
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, lineterminator="\n")
        writer.writerows(rows)


def run_deid(raw_csv, registry, out_dir):
    result = subprocess.run(
        [
            sys.executable,
            str(ROOT / "pipeline" / "deid.py"),
            str(raw_csv),
            "--member-code",
            "M1",
            "--registry",
            str(registry),
            "--out-dir",
            str(out_dir),
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(result.stdout)


class DeidTests(unittest.TestCase):
    def test_libre_deid_removes_header_pii_and_preserves_glucose_rows(self):
        TEST_TMP.mkdir(exist_ok=True)
        with tempfile.TemporaryDirectory(dir=TEST_TMP) as tmp:
            tmp_path = Path(tmp)
            raw_csv = tmp_path / "raw.csv"
            registry = tmp_path / "members.json"
            out_dir = tmp_path / "cleaned"
            write_synthetic_libre(raw_csv)

            metadata = run_deid(raw_csv, registry, out_dir)
            cleaned_path = Path(metadata["source_uri"])
            cleaned_text = cleaned_path.read_text(encoding="utf-8")

            self.assertNotIn("Jane Example", cleaned_text)
            self.assertNotIn("1977-04-03", cleaned_text)
            self.assertIn(metadata["member_id"], cleaned_text)
            self.assertEqual(metadata["device_type"], "libre2")
            self.assertEqual(metadata["stripped_by"], "deid-py-v1")

            with cleaned_path.open("r", encoding="utf-8", newline="") as handle:
                rows = list(csv.reader(handle))
            glucose_rows = [
                row for row in rows if row and row[0].startswith("2026-01-01")
            ]
            self.assertEqual(
                glucose_rows,
                [
                    ["2026-01-01 00:00", "0", "5.4"],
                    ["2026-01-01 00:15", "0", "5.7"],
                    ["2026-01-01 00:30", "0", "6.1"],
                ],
            )

    def test_patient_report_variant_with_unlabeled_pii_is_scrubbed(self):
        # The "Patient report" export variant carries the name after a
        # "Generated by" cell and a bare "<name>,<DOB>" line — no field labels.
        TEST_TMP.mkdir(exist_ok=True)
        with tempfile.TemporaryDirectory(dir=TEST_TMP) as tmp:
            tmp_path = Path(tmp)
            raw_csv = tmp_path / "raw.csv"
            rows = [
                ["Patient report", "Generated on", "29-06-2026 14:34 UTC", "Generated by", "ken roe"],
                ["Ken Roe", "27-12-1960"],
                ["Device", "Serial Number", "Device Timestamp", "Record Type", "Historic Glucose mmol/L"],
                ["FreeStyle Libre 2", "SER", "07-12-2025 12:44", "0", "7.1"],
            ]
            with raw_csv.open("w", encoding="utf-8", newline="") as handle:
                csv.writer(handle, lineterminator="\n").writerows(rows)

            metadata = run_deid(raw_csv, tmp_path / "members.json", tmp_path / "cleaned")
            cleaned_text = Path(metadata["source_uri"]).read_text(encoding="utf-8")

            self.assertNotIn("Ken Roe", cleaned_text)
            self.assertNotIn("ken roe", cleaned_text)
            self.assertNotIn("27-12-1960", cleaned_text)
            self.assertIn(metadata["member_id"], cleaned_text)
            self.assertIn("07-12-2025 12:44,0,7.1", cleaned_text)

    def test_deid_is_deterministic_with_existing_registry(self):
        TEST_TMP.mkdir(exist_ok=True)
        with tempfile.TemporaryDirectory(dir=TEST_TMP) as tmp:
            tmp_path = Path(tmp)
            raw_csv = tmp_path / "raw.csv"
            registry = tmp_path / "members.json"
            out_dir = tmp_path / "cleaned"
            write_synthetic_libre(raw_csv)

            first = run_deid(raw_csv, registry, out_dir)
            first_bytes = Path(first["source_uri"]).read_bytes()
            second = run_deid(raw_csv, registry, out_dir)
            second_bytes = Path(second["source_uri"]).read_bytes()

            self.assertEqual(first["member_id"], second["member_id"])
            self.assertEqual(first["sha256"], second["sha256"])
            self.assertEqual(first_bytes, second_bytes)


if __name__ == "__main__":
    unittest.main()