import csv
import json
import sys
import unittest
from datetime import date, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "pipeline"))

from build_payload import (  # noqa: E402
    build_cycles,
    burst_events,
    cycle_windows,
    day_notes,
    grid_days,
    parse_export,
    wear_runs,
)


HEADER = [
    "Device", "Serial Number", "Device Timestamp", "Record Type",
    "Historic Glucose mmol/L", "Scan Glucose mmol/L",
    "Non-numeric Rapid-Acting Insulin", "Rapid-Acting Insulin (units)",
    "Non-numeric Food", "Carbohydrates (grams)", "Carbohydrates (servings)",
    "Non-numeric Long-Acting Insulin", "Long-Acting Insulin Value (units)",
    "Notes", "Strip Glucose mmol/L", "Ketone mmol/L",
    "Meal Insulin (units)", "Correction Insulin (units)", "User Change Insulin (units)",
]


def row(ts, rtype, hist="", scan="", note=""):
    cells = ["FreeStyle Libre 2", "SERIAL", ts, rtype, hist, scan] + [""] * 7 + [note] + [""] * 5
    return cells


def write_export(path, rows, glucose_header="Historic Glucose mmol/L"):
    header = list(HEADER)
    header[4] = glucose_header
    all_rows = [
        ["Patient report", "Generated on", "29-06-2026 14:34 UTC", "Generated by", "someone"],
        ["Some Person", "01-01-1960"],
        header,
        *rows,
    ]
    with path.open("w", encoding="utf-8", newline="") as handle:
        csv.writer(handle, lineterminator="\n").writerows(all_rows)


class ParseTests(unittest.TestCase):
    def setUp(self):
        (ROOT / ".test-tmp").mkdir(exist_ok=True)

    def _parse(self, rows, **kw):
        path = ROOT / ".test-tmp" / "synthetic.csv"
        write_export(path, rows, **kw)
        return parse_export(path)

    def test_reading_scan_note_extraction(self):
        parsed = self._parse([
            row("07-12-2025 12:44", "0", hist="7.1"),
            row("07-12-2025 12:50", "1", scan="8.3"),
            row("07-12-2025 13:04", "6", note="Lunch"),
            row("07-12-2025 13:05", "6", note=""),        # blank note dropped
            row("07-12-2025 13:06", "5"),                 # food flag ignored
        ])
        self.assertEqual(parsed["readings"], [(datetime(2025, 12, 7, 12, 44), 7.1)])
        self.assertEqual(parsed["scans"], [(datetime(2025, 12, 7, 12, 50), 8.3)])
        self.assertEqual(parsed["notes"], [(datetime(2025, 12, 7, 13, 4), "Lunch")])

    def test_multiline_note_joined(self):
        parsed = self._parse([row("07-12-2025 19:02", "6", note="Beef\nwith rice\n")])
        self.assertEqual(parsed["notes"][0][1], "Beef · with rice")

    def test_mgdl_converted_to_mmol(self):
        parsed = self._parse(
            [row("07-12-2025 12:44", "0", hist="126")],
            glucose_header="Historic Glucose mg/dL",
        )
        self.assertEqual(parsed["readings"][0][1], 7.0)


class GridTests(unittest.TestCase):
    def test_snap_to_grid_and_midnight_rollover(self):
        readings = [
            (datetime(2026, 1, 1, 12, 44), 7.1),   # -> 12:45
            (datetime(2026, 1, 1, 23, 53), 6.0),   # -> next day 00:00
        ]
        days = grid_days(readings, date(2026, 1, 1))
        self.assertEqual(days[0], [[765, 7.1]])
        self.assertEqual(days[1], [[0, 6.0]])

    def test_duplicate_slot_takes_median(self):
        readings = [
            (datetime(2026, 1, 1, 12, 44), 7.0),
            (datetime(2026, 1, 1, 12, 46), 8.0),
            (datetime(2026, 1, 1, 12, 47), 9.0),
        ]
        days = grid_days(readings, date(2026, 1, 1))
        self.assertEqual(days[0], [[765, 8.0]])


class CycleWindowTests(unittest.TestCase):
    def test_gap_splits_wear_and_short_tail_dropped(self):
        readings = (
            # 15 calendar dates Jan 1-15 -> one cycle Jan 1-14, 1-day tail dropped
            [(datetime(2026, 1, d, h, 0), 5.5) for d in range(1, 16) for h in (6, 18)]
            # >12h gap, second wear Feb 1-12 (12 days >= min 10) -> second cycle
            + [(datetime(2026, 2, d, h, 0), 5.5) for d in range(1, 13) for h in (6, 18)]
        )
        windows = cycle_windows(wear_runs(readings), min_days=10)
        self.assertEqual(windows, [
            (date(2026, 1, 1), date(2026, 1, 14)),
            (date(2026, 2, 1), date(2026, 2, 14)),
        ])

    def test_back_to_back_sensors_chunked(self):
        readings = [(datetime(2026, 3, d, h, 0), 5.0) for d in range(1, 29) for h in (6, 18)]
        windows = cycle_windows(wear_runs(readings), min_days=10)
        self.assertEqual(windows, [
            (date(2026, 3, 1), date(2026, 3, 14)),
            (date(2026, 3, 15), date(2026, 3, 28)),
        ])


class EventTests(unittest.TestCase):
    def test_cluster_join_split_and_min_taps(self):
        base = datetime(2026, 1, 2, 19, 23)
        scans = (
            # burst A: 6 taps, 9-min internal gap still joins, peaks at 8.8 -> HIGH
            [(base.replace(minute=23 + i), 6.0 + i * 0.5) for i in range(4)]
            + [(base.replace(minute=35), 8.5), (base.replace(minute=36), 8.8)]
            # 20-min gap -> new cluster, but only 3 taps -> dropped
            + [(base.replace(minute=56), 5.0), (base.replace(minute=57), 5.1), (base.replace(minute=58), 5.2)]
        )
        events = burst_events(scans, date(2026, 1, 1))
        self.assertEqual(len(events), 1)
        ev = events[0]
        self.assertEqual(ev["kind"], "HIGH")
        self.assertEqual(ev["taps"], 6)
        self.assertEqual(ev["day"], 1)
        self.assertEqual(ev["slot"], 1170)     # 19:23 -> 19:30
        self.assertEqual(ev["t0"], "19:30")
        self.assertEqual(ev["hi"], 8.8)

    def test_low_kind_beats_high(self):
        scans = [(datetime(2026, 1, 1, 10, i), g) for i, g in enumerate([3.4, 3.6, 3.8, 4.2, 5.0, 8.0])]
        events = burst_events(scans, date(2026, 1, 1))
        self.assertEqual(events[0]["kind"], "LOW")

    def test_burst_crossing_midnight_stays_monotonic(self):
        scans = [
            (datetime(2026, 1, 1, 23, 57), 5.0), (datetime(2026, 1, 1, 23, 58), 5.1),
            (datetime(2026, 1, 1, 23, 59), 5.2), (datetime(2026, 1, 2, 0, 1), 5.3),
            (datetime(2026, 1, 2, 0, 2), 5.4), (datetime(2026, 1, 2, 0, 3), 5.5),
        ]
        events = burst_events(scans, date(2026, 1, 1))
        ts = [t for t, _ in events[0]["burst"]]
        self.assertEqual(ts, sorted(ts))
        self.assertEqual(events[0]["day"], 0)
        self.assertGreater(ts[-1], 1440)


class BuildTests(unittest.TestCase):
    def test_records_shape_and_notes_keyed_by_day(self):
        parsed = {
            "readings": [(datetime(2026, 1, d, h, 0), 5.5) for d in range(1, 15) for h in range(24)],
            "scans": [],
            "notes": [(datetime(2026, 1, 3, 12, 0), "Lunch note")],
        }
        records = build_cycles(parsed, min_days=10)
        self.assertEqual(len(records), 1)
        rec = records[0]
        self.assertEqual(rec["cycle_number"], 1)
        self.assertEqual(rec["start_date"], "2026-01-01")
        self.assertEqual(rec["end_date"], "2026-01-14")
        self.assertEqual(rec["label"], "Jan 1 – Jan 14, 2026")
        payload = json.loads(rec["payload"])
        self.assertEqual(len(payload["days"]), 14)
        self.assertEqual(payload["notes"], {"2": [{"time": "12:00", "text": "Lunch note"}]})
        self.assertEqual(payload["sensor"], 25)   # hourly readings = 24/96

    def test_note_outside_window_dropped(self):
        notes = day_notes([(datetime(2026, 2, 1, 9, 0), "late note")], date(2026, 1, 1))
        self.assertEqual(notes, {})


if __name__ == "__main__":
    unittest.main()
