"""De-identify CGM exports before anything reaches the application database."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from uuid import uuid4


DEVICE_PROFILES = {
    "libre2": {
        "device_type": "libre2",
        "header_rows": None,
        "table_header_markers": ("Device Timestamp", "Record Type"),
        "slice_min": 15,
        "cycle_days": 14,
    }
}

DEFAULT_DEVICE_PROFILE = "libre2"
PII_TOKEN = "member_uuid"


def _normalized(value: str) -> str:
    return "".join(ch for ch in value.lower() if ch.isalnum())


def _read_csv(path: Path) -> list[list[str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.reader(handle))


def _write_csv(path: Path, rows: list[list[str]]) -> bytes:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, lineterminator="\n")
        writer.writerows(rows)
    return path.read_bytes()


def _load_registry(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8") as handle:
        data = json.load(handle)
    if not isinstance(data, dict):
        raise ValueError("member registry must be a JSON object")
    return {str(key): str(value) for key, value in data.items()}


def _save_registry(path: Path, registry: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        json.dump(dict(sorted(registry.items())), handle, indent=2)
        handle.write("\n")


def _member_id_for_code(registry_path: Path, member_code: str) -> str:
    registry = _load_registry(registry_path)
    if member_code not in registry:
        registry[member_code] = str(uuid4())
        _save_registry(registry_path, registry)
    return registry[member_code]


def _table_header_index(rows: list[list[str]], profile: dict) -> int:
    configured = profile.get("header_rows")
    if configured is not None:
        return int(configured)

    markers = {_normalized(marker) for marker in profile["table_header_markers"]}
    for index, row in enumerate(rows):
        row_tokens = {_normalized(cell) for cell in row}
        if markers.issubset(row_tokens):
            return index
    raise ValueError("could not locate CGM table header row")


def scrub_rows(rows: list[list[str]], member_id: str, profile: dict) -> list[list[str]]:
    """Replace everything above the CGM table with one provenance row.

    The pre-table region is dropped outright rather than pattern-matched:
    LibreView export variants disagree about how PII appears there (labeled
    "Patient Name" fields in one, a bare "Ken Roe,27-12-1960" line and a
    "Generated by,<name>" cell in the "Patient report" variant), and nothing
    downstream reads that region. What isn't kept can't leak.
    """
    header_rows = _table_header_index(rows, profile)
    return [[PII_TOKEN, member_id]] + [list(row) for row in rows[header_rows:]]


def deidentify(
    raw_csv: Path,
    member_code: str,
    registry_path: Path,
    out_dir: Path,
    device_profile: str = DEFAULT_DEVICE_PROFILE,
) -> dict[str, str | int]:
    if device_profile not in DEVICE_PROFILES:
        known = ", ".join(sorted(DEVICE_PROFILES))
        raise ValueError(f"unknown device profile '{device_profile}' (known: {known})")

    profile = DEVICE_PROFILES[device_profile]
    member_id = _member_id_for_code(registry_path, member_code)
    rows = _read_csv(raw_csv)
    scrubbed = scrub_rows(rows, member_id, profile)

    raw_sha = hashlib.sha256(raw_csv.read_bytes()).hexdigest()
    out_path = out_dir / f"{member_code}_{raw_sha[:12]}_cleaned.csv"
    cleaned_bytes = _write_csv(out_path, scrubbed)
    cleaned_sha = hashlib.sha256(cleaned_bytes).hexdigest()

    return {
        "member_id": member_id,
        "device_type": profile["device_type"],
        "sha256": cleaned_sha,
        "stripped_by": "deid-py-v1",
        "stripped_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "source_uri": str(out_path),
        "slice_min": profile["slice_min"],
        "cycle_days": profile["cycle_days"],
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Strip PII from CGM CSV exports.")
    parser.add_argument("raw_csv", type=Path)
    parser.add_argument("--member-code", required=True)
    parser.add_argument("--registry", required=True, type=Path)
    parser.add_argument("--out-dir", required=True, type=Path)
    parser.add_argument(
        "--device-profile",
        default=DEFAULT_DEVICE_PROFILE,
        choices=sorted(DEVICE_PROFILES),
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    metadata = deidentify(
        raw_csv=args.raw_csv,
        member_code=args.member_code,
        registry_path=args.registry,
        out_dir=args.out_dir,
        device_profile=args.device_profile,
    )
    print(json.dumps(metadata, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
